package components.inventory;

public enum SubTypeWeapon implements SubSubType {
	IRON_DAGGAR, STEEL_DAGGAR, SWORD, MACE, BATTLEAXE, LONGSWORD, LONGBOW, SHORTBOW, CROSSBOW, QUICK_CROSSBOW, FIRE_STAFF, ICE_STAFF, EARTH_STAFF
}
