package gui;

public enum ButtonType {
	NEW_GAME, LOAD_GAME, OPTIONS, EXIT,
	LEVEL1, LEVEL2,
	WARRIOR, ARCHER, MAGE,
	BACK,
	SOUND, CONTROLS,
	RESUME, MAIN_MENU, INVENTORY, SKILLS, MAGIC, SAVE, MAP, 
	HEALTH, HEALTH_REGEN, MANA, MANA_REGEN,
	POTIONS_UPGRADE, INVENTORY_UPGRADE,
	OTHER
}
