package gui;

public enum TypeButton {
	NEW_GAME, LOAD_GAME, OPTIONS, EXIT, LEVEL1, LEVEL2, LEVEL3, WARRIOR, ARCHER, MAGE, BATTLE_MAGE, ROGUE, BACK, SOUND, CONTROLS, MUTE, RESUME, MAIN_MENU, INVENTORY, SKILLS, UPGRADES, SAVE, MAP, HEALTH, HEALTH_REGEN, MANA, MANA_REGEN, POTIONS_UPGRADE, INVENTORY_UPGRADE, SAVE_GAME, OTHER
}
